/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 book.glb 
Author: katrin.kor (https://sketchfab.com/katrin.701)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/viking-book-c23b8c487c3c455cb8ff970a3ec3a5c2
Title: Viking book
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
 function Book(props) {
  const { nodes, materials } = useGLTF('/book.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.MeshSG} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.lambert5SG} />
      </group>
    </group>
  )
}

useGLTF.preload('/book.glb')

export default Book
