/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 idea_lamp.glb 
Author: Helsingr (https://sketchfab.com/helsingr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/idea-lamp-4c2b7bdc188e4c74b5392e4d967a1a0a
Title: Idea lamp
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function IdeaLamp(props) {
  const { nodes, materials } = useGLTF('/models/idea_lamp.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Base__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Glass__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.Cube__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.BaseIsolation__0.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/models/idea_lamp.glb')
